In [7]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv('spam.csv',encoding='ISO-8859-1')

In [9]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [10]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [12]:
df.sample()

v1                                 v2
807  ham  Boooo you always work. Just quit.

In [13]:
df.rename(columns={'v1':'target1','v2':'target2'},inplace=True)

In [14]:
df.head()

target1                                            target2
0     ham  Go until jurong point, crazy.. Available only ...
1     ham                      Ok lar... Joking wif u oni...
2    spam  Free entry in 2 a wkly comp to win FA Cup fina...
3     ham  U dun say so early hor... U c already then say...
4     ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [16]:
df['target1']=encoder.fit_transform(df['target1'])

In [17]:
df.head()

target1                                            target2
0        0  Go until jurong point, crazy.. Available only ...
1        0                      Ok lar... Joking wif u oni...
2        1  Free entry in 2 a wkly comp to win FA Cup fina...
3        0  U dun say so early hor... U c already then say...
4        0  Nah I don't think he goes to usf, he lives aro...

In [18]:
df.duplicated().sum()

403

In [19]:
df=df.drop_duplicates(keep='first')

In [20]:
df.duplicated().sum()

0

In [22]:
import matplotlib.pyplot as plt
plt.pie(df['target1'].value_counts(),labels=['ham','spam'],autopct="%0.3f")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [23]:
 df.shape

(5169, 2)

In [24]:
df['target2'].value_counts()

target2
Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                               1
Wake me up at  &lt;#&gt;  am morning:)                                                                                                                        1
I will reach ur home in  &lt;#&gt;  minutes                                                                                                                   1
Wait.i will come out.. &lt;#&gt;  min:)                                                                                                                       1
R u here yet? I'm wearing blue shirt n black pants.                                                                                                           1
                                                                                                                                                             ..
;-( oh well, c u later          

In [25]:
df['target1'].value_counts()

target1
0    4516
1     653
Name: count, dtype: int64

In [26]:
import nltk

ModuleNotFoundError: No module named 'nltk'

In [27]:
nltk.download('punkt')

NameError: name 'nltk' is not defined

In [28]:
df['num_characters']=df['target2'].apply(len)

In [29]:
df['num_words']=df['target2'].apply(lambda x:len(nltk.word_tokenize(x)))

NameError: name 'nltk' is not defined

In [ ]:
df['num_sentences']=df['target2'].apply(lambda x:len(nltk.sent_tokenize(x)))

In [30]:
df.head()

target1                                            target2  num_characters
0        0  Go until jurong point, crazy.. Available only ...             111
1        0                      Ok lar... Joking wif u oni...              29
2        1  Free entry in 2 a wkly comp to win FA Cup fina...             155
3        0  U dun say so early hor... U c already then say...              49
4        0  Nah I don't think he goes to usf, he lives aro...              61

In [31]:
df[['num_characters','num_words','num_sentences']].describe()

KeyError: "['num_words', 'num_sentences'] not in index"

In [ ]:
df[df['target1']==0][['num_characters','num_words','num_sentences']].describe()

num_characters    num_words  num_sentences
count     4516.000000  4516.000000    4516.000000
mean        70.459256    17.123782       1.820195
std         56.358207    13.493970       1.383657
min          2.000000     1.000000       1.000000
25%         34.000000     8.000000       1.000000
50%         52.000000    13.000000       1.000000
75%         90.000000    22.000000       2.000000
max        910.000000   220.000000      38.000000

In [ ]:
df[df['target1']==1][['num_characters','num_words','num_sentences']].describe()

num_characters   num_words  num_sentences
count      653.000000  653.000000     653.000000
mean       137.891271   27.667688       2.970904
std         30.137753    7.008418       1.488425
min         13.000000    2.000000       1.000000
25%        132.000000   25.000000       2.000000
50%        149.000000   29.000000       3.000000
75%        157.000000   32.000000       4.000000
max        224.000000   46.000000       9.000000

In [32]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [33]:
plt.figure(figsize=(12,7))
sns.histplot(df[df['target1']==0]['num_characters'])
sns.histplot(df[df['target1']==1]['num_characters'])

NameError: name 'plt' is not defined

In [34]:
sns.histplot(df[df['target1']==1]['num_characters'],color="red")

NameError: name 'sns' is not defined

In [35]:
df['num_characters'].value_counts()

num_characters
22     91
24     91
32     90
23     86
38     82
       ..
375     1
431     1
2       1
790     1
273     1
Name: count, Length: 274, dtype: int64

In [36]:
sns.pairplot(df,hue='target1')

NameError: name 'sns' is not defined

In [37]:
sns.heatmap(df.corr(),annot=True)

NameError: name 'sns' is not defined

In [38]:
import nltk
nltk.download('stopwords')

ModuleNotFoundError: No module named 'nltk'

In [39]:
from nltk.corpus import stopwords
stopwords.words('english')

ModuleNotFoundError: No module named 'nltk'

In [40]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [41]:
def transform_target2(target2):
  target2=target2.lower()
  target2=nltk.word_tokenize(target2)

  y=[]
  for i in target2:
    if i.isalnum():
      y.append(i)


      target2=y[:]
      y.clear()

      for i in target2:
        if i not in stopwords.words('english'):
          y.append(i)


  return " ".join(y)



In [42]:
transform_target2("I loved you tube ")

NameError: name 'nltk' is not defined

In [43]:
df['target2'][1000]

'No..but heard abt tat..'

In [44]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
ps.stem('loving')

ModuleNotFoundError: No module named 'nltk'

In [45]:
df['transformed_target']=df['target2'].apply(transform_target2)

NameError: name 'nltk' is not defined

In [46]:
df.head()

target1                                            target2  num_characters
0        0  Go until jurong point, crazy.. Available only ...             111
1        0                      Ok lar... Joking wif u oni...              29
2        1  Free entry in 2 a wkly comp to win FA Cup fina...             155
3        0  U dun say so early hor... U c already then say...              49
4        0  Nah I don't think he goes to usf, he lives aro...              61

In [47]:
from wordcloud import WordCloud
wc=WordCloud(width=500,height=500,min_font_size=10,background_color='white')

ModuleNotFoundError: No module named 'wordcloud'

In [48]:
spam_wc=wc.generate(df[df['target1']==1]['target2'].str.cat(sep=""))

NameError: name 'wc' is not defined

In [49]:
plt.figure(figsize=(15,6))
plt.imshow(spam_wc)

NameError: name 'plt' is not defined

In [50]:
ham_wc=wc.generate(df[df['target1']==0]['target2'].str.cat(sep=""))

NameError: name 'wc' is not defined

In [51]:
plt.figure(figsize=(15,6))
plt.imshow(ham_wc)

NameError: name 'plt' is not defined

In [52]:
spam_corpus=[]
for msg in df[df['target1']==1]['transformed_target'].tolist():
  for word in msg.split():
    spam_corpus.append(word)

KeyError: 'transformed_target'

In [53]:
len(spam_corpus)

0

In [54]:
from collections import Counter
sns.barplot(pd.DataFrame(Counter(spam_corpus).most_common(30))[0],)
plt.xticks(rotation='vertical')
plt.show()

NameError: name 'sns' is not defined

In [55]:
ham_corpus=[]
for msg in df[df['target1']==1]['transformed_target'].tolist():
  for word in msg.split():
    spam_corpus.append(word)

KeyError: 'transformed_target'

In [56]:
len(ham_corpus)

0

In [57]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv=CountVectorizer
tfidf=TfidfVectorizer(max_features=3000)

In [84]:
x=df['target1'].values

In [85]:
 y=df['target'].values

KeyError: 'target'

In [86]:
print(x)

[0 0 1 ... 0 0 0]


In [87]:

x.shape

(5169,)

In [88]:
y.shape

(5169,)

In [89]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [90]:
x_train

array([0, 0, 0, ..., 0, 0, 0])

In [91]:
x_test

array([0, 0, 0, ..., 0, 0, 0])

In [92]:
y_train


array([0, 0, 0, ..., 0, 0, 0])

In [93]:

x_test

array([0, 0, 0, ..., 0, 0, 0])

In [94]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [95]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [96]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [97]:

x_train = x_train.reshape(-1, 1)
x_test = x_test.reshape(-1, 1)

In [98]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier,ExtraTreesClassifier

In [99]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
Ada=AdaBoostClassifier()
ET=ExtraTreesClassifier()
sc=SVC()

In [100]:
mnb.fit(x_train,y_train)
y_pred2=mnb.predict(x_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

0.8665377176015474
[[896   0]
 [138   0]]
0.0


c:\Users\jhama\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [101]:
bnb.fit(x_train,y_train)
y_pred3=bnb.predict(x_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

1.0
[[896   0]
 [  0 138]]
1.0


In [102]:
dt.fit(x_train,y_train)
y_pred4=dt.predict(x_test)
print(accuracy_score(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))
print(precision_score(y_test,y_pred4))

1.0
[[896   0]
 [  0 138]]
1.0


In [103]:
rf.fit(x_train,y_train)
y_pred5=rf.predict(x_test)
print(accuracy_score(y_test,y_pred5))
print(confusion_matrix(y_test,y_pred5))
print(precision_score(y_test,y_pred5))

1.0
[[896   0]
 [  0 138]]
1.0


In [104]:
sc.fit(x_train,y_train)
y_pred6=sc.predict(x_test)
print(accuracy_score(y_test,y_pred6))
print(confusion_matrix(y_test,y_pred6))
print(precision_score(y_test,y_pred6))

1.0
[[896   0]
 [  0 138]]
1.0


In [105]:
Ada.fit(x_train,y_train)
y_pred7=Ada.predict(x_test)
print(accuracy_score(y_test,y_pred7))
print(confusion_matrix(y_test,y_pred7))
print(precision_score(y_test,y_pred7))

1.0
[[896   0]
 [  0 138]]
1.0


c:\Users\jhama\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [106]:

ET.fit(x_train,y_train)
y_pred8=ET.predict(x_test)
print(accuracy_score(y_test,y_pred8))
print(confusion_matrix(y_test,y_pred8))
print(precision_score(y_test,y_pred8))

1.0
[[896   0]
 [  0 138]]
1.0


In [107]:
clfs={
  'SVC':sc,
  'NB':mnb,
  'DT':dt,
  'RF':rf,
  'Ada':Ada,
  'ET':ET
}

In [108]:
def train_classifier(clf,x_train,y_train,x_test,y_test):
  clf.fit(x_train,y_train)
  y_pred=clf.predict(x_test)
  accuracy=accuracy_score(y_test,y_pred)
  precision=precision_score(y_test,y_pred)

  return accuracy.precision

In [109]:


import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(mnb,open('model.pkl','wb'))

In [110]:
pickle.load(open("model.pkl","rb"))


MultinomialNB()